language: php

services:
  - docker

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 1

env:
  global:
    - SERVICE_NAME=nbbib.lib.unb.ca
    - AMAZON_ECR_REGION=us-east-1
    - DEPLOY_BRANCHES=dev,prod
    - DEPLOYMENT_FINISHED_MARKER=99_report_as_complete
    - DOCKER_UPSTREAM_IMAGE=unblibraries/drupal:8.x-1.x
    - OLD_IMAGES_TO_KEEP=2
    - SERVICE_DEPLOY_PORT=80
    - SERVICE_TEST_UP_PATH=/user

before_install:
  - curl -sSL https://raw.githubusercontent.com/unb-libraries/CargoDock/drupal-8.x-1.x/travis/deploy.sh | sh
  - CargoDock/travis/beforeInstall.sh

before_script:
  - CargoDock/travis/beforeScript.sh

script:
  - CargoDock/travis/testInstance.sh

after_success:
  - CargoDock/travis/afterSuccess.sh

notifications:
  slack:
    rooms:
      secure: pZnWwLSsPF8sV8OZpHBKmU25BLwEbAbj74lDstxwLS7+oR5sxrT1ZsZi+9QG3BYLCedX8iN9eqpeeYC14HnN6CKiopPUxDsYI4ARx2MzPnDxIWAcgTvuVR+34Mv5BWllT6/BdCmRrDQ8OPWR081uzxTqXgiX80744C7qNWvjL9uSX27QGBfiSK58Sn1EZM3hFVxTQSE4Yi+qjCxce7cOraVDK4WBAmJPWWbVnOOfLEDHGX1ITk+2HgUQnFxgZ+0wRTe6PEZbHBiESkNNcVeCqmuaIs9XzKsY3l5VV/OuSyhLTnJb3S4p11VH7TOvBE9ItbnGTd4bzsmXGYhckOiWX1SWMmjE1ONFcI0gaMvr5akpKoLGfnYRrMZhsJhR0W+Fn6lT5KKpuY2nGmYktLJ85ZWCLZ1JPtRWICl8nLabF57/iYwMF7kWyDoaa3XXlJbqaF3U1czV8eOtSlH4c90JkrR98IEmsnNPaG1L4fr+Q9yJtKLG89guNK7OdtE+nRHghYWOosFJulca0ccRTh0ZSkUqfFNM1vcODxuL5sQh4MDKZ/L07FIfRLzpBURWV8Xx6sy2SMQgI7zxYSuU6kkHyfDESRKQt0XpXXcp9686yACmujjsULcTvuZksSAdS2LOOOf2edRwfKSw7N2QfgMAjKzlINyTbSrA+um1raQnEs0=
    on_start: always
    on_success: always
