language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - echo "$DOCKER_CLOUD_USER_PASS" | docker login --username "$DOCKER_CLOUD_USER_NAME" --password-stdin
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH
  - vendor/unb-libraries/dockworker/scripts/travis/notifyNewRelicDeployment.sh

notifications:
  slack:
    rooms:
      secure: AXgOsYG+1v50FGgGmTUdp4oB4X/cH2hC6rga5w2B2nu7cF4boxoX7AghudYqAupK2KM2I1Hyd9+5K2Nk1kMa2O9YJS/TbKnz8olByu6XCCa/gKRQVCrvRCaiCnwBb+efi/dH+JhEqmv4PZ2GlbJFb07THRm2YbxQOHE/t66WTYIbdW9vnwsi9OJmQF9yNxNW1CSMpT8L+zz715TA1t2RRPgunsqHNdoq6S4b07IX+bfGATGGcx6sgMOh0AK/Fv8HnXN4NMUxxIQWu9XesLqLUMsEs7PqEQJB2EDxX4IoDRK/qmZ+nVe945i+quY/fCoA+PxjNZab66Nto7HjmssuBYBiS9nwUgoaBGTuj4iz9ruy18vjz3COLt1Z1rF+jnQXBi0iBZtG2CfxnYAe011qIMV+1uYrHbpwH6PqMgerTudwFuf771wZrB8spiB0jKn0aqJQtRoAjKHv6oc4NC8ByiCKtpH3WJV/BAHgCU6rmTthhHsXEtoqmy4kdaaeFyxRjQzwP8TdqwVuF6suxW6ZOoUNsdNRThWY9Hc9s42livgpEpPi93zdwXBe5a9KTNrLDbZ8F35fCWB/4P7OvYmjxcUJN74ff29W5pNhoSdGpDEiDLawwXxW7RsCKypJ+HYYDQNsDkptQplYF4o1Z6g3YZ0goaowWR2N0JTuMXbtOCo=
    on_start: always
    on_success: always
