<?php

/**
 * @file
 * Contains nbbib_core.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function nbbib_core_theme($existing, $type, $theme, $path) {
  return [
    'nbbib_intro' => [
      'variables' => [],
    ],
    'nbbib_about' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nbbib_core_form_views_exposed_form_alter(&$form, $form_state, $form_id) {

  // Target specific exposed form (bibliography).
  if ($form['#id'] == "views-exposed-form-nb-bibliography-citations-page-1") {
    $form['bibliographic_type']['#type'] = "select";
    $form['bibliographic_type']['#size'] = NULL;
    $form['bibliographic_type']['#validated'] = TRUE;

    // Override bibliographic_type input to dropdown.
    $form['bibliographic_type']['#options'] = [
      '' => t('- Any -'),
      'Book' => t('Book'),
      'Book Section' => t('Book Section'),
      'Journal Article' => t('Journal Article'),
      'Thesis' => t('Thesis'),
    ];

    $form['bibliographic_type']['#default_value'] = 'All';

    // Override collections input to dropdown.
    $form['collections_5']['#type'] = "select";
    $form['collections_5']['#size'] = NULL;
    $form['collections_5']['#validated'] = TRUE;

    $form['collections_5']['#options'] = [
      '' => t('- Any -'),
      'Religion: Anglican' => t('Religion: Anglican'),
      'New Brunswickana' => t('New Brunswickana'),
    ];

    $form['collections_5']['#default_value'] = 'All';
  }

}

/**
 * Adds a top priority handler to the 'submit' action of the specified form.
 */
function top_submit_handler(&$form, $handler) {
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) &&
    $form['actions'][$action]['#type'] === 'submit') {
      array_unshift($form['actions'][$action]['#submit'], $handler);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function nbbib_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Attach JS library.
  $form['#attached']['library'][] = 'nbbib_core/contrib-ief';
  // Target all reference add/edit forms.
  $target_forms = [
    'yabrm_book_add_form',
    'yabrm_book_edit_form',
    'yabrm_book_section_add_form',
    'yabrm_book_section_edit_form',
    'yabrm_thesis_add_form',
    'yabrm_thesis_edit_form',
    'yabrm_journal_article_add_form',
    'yabrm_journal_article_edit_form',
  ];

  if (in_array($form_id, $target_forms)) {
    top_submit_handler($form, 'clr_blank_contribs');
  }
}

/**
 * Submit handler for yabrm_book_edit. Removes empty contributors before saving to avoid errors.
 */
function clr_blank_contribs(&$form, FormStateInterface $form_state) {
  $contribs = $form_state->getValue('contributors');

  foreach ($contribs as $key => $contrib) {
    if (empty($contrib['subform']['field_yabrm_contributor_person']['entities'])) {
      if (is_int($key)) {
        unset($contribs[$key]);
      }
    }
  }

  $form_state->setValue('contributors', $contribs);
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function nbbib_core_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  // Contributor inline_entity_form hook. Add after-build handler.
  $entity_form['#after_build'][] = 'format_contrib_subform';
  // Attach JS library.
  $entity_form['#attached']['library'][] = 'nbbib_core/contrib-ief';
  // Add custom element validation.
  $entity_form['#element_validate'][] = 'validate_contrib_subform';
}

/**
 * After-build handler for contributors. Adds conditional state formatting.
 */
function format_contrib_subform($form, &$form_state) {
  // Institution name only enabled if both first and last names are empty.
  $form['institution_name']['#states'] = [
    'enabled' => [
      ':input[name="contributors[0][subform][field_yabrm_contributor_person][form][inline_entity_form][entities][0][form][first_name][0][value]"]' => ['empty' => TRUE],
      ':input[name="contributors[0][subform][field_yabrm_contributor_person][form][inline_entity_form][entities][0][form][last_name][0][value]"]' => ['empty' => TRUE],
    ],
  ];

  // First and last name only enabled if institution name is empty.
  $form['first_name']['#states'] = $form['last_name']['#states'] = [
    'enabled' => [
      ':input[name="contributors[0][subform][field_yabrm_contributor_person][form][inline_entity_form][entities][0][form][institution_name][0][value]"]' => ['filled' => FALSE],
    ],
  ];

  // Name and sort name are hidden.
  $form['name']['#attributes']['class'][] = 'hidden';
  $form['sort_name']['#attributes']['class'][] = 'hidden';

  return $form;
}

/**
 * Custom validation handler for contributors. Adds conditional state formatting.
 */
function validate_contrib_subform($element, &$form_state) {
  $first_name = $element['first_name']['widget'][0]['value']['#value'];
  $last_name = $element['last_name']['widget'][0]['value']['#value'];
  $institution_name = $element['institution_name']['widget'][0]['value']['#value'];

  if (empty($institution_name)) {
    if (empty($first_name) and empty($last_name)) {
      $form_state->setErrorByName('Contributor Name', t('Either institution or individual names are required.'));
    }
    elseif (empty($first_name) or empty($last_name)) {
      $form_state->setErrorByName('Contributor Name', t('Full names are required for individual contributors.'));
    }
  }
  elseif (!empty($last_name) or !empty($last_name)) {
    $form_state->setErrorByName('Contributor Name', t('Either institution or individual names are allowed. Not both.'));
  }
}

/**
 * Implements hook_ENTITY_TYPE_ID_presave().
 */
function nbbib_core_yabrm_contributor_presave(EntityInterface $entity) {
  // Pupulate name (display) and sort name on save.
  $first_name = trim($entity->getFirstName());
  $last_name = trim($entity->getLastName());
  $institution_name = trim($entity->getInstitutionName());
  $name = $sort_name = '';

  if (!empty($institution_name)) {
    $name = $sort_name = $institution_name;
  }
  elseif (!empty($last_name)) {
    $name .= $last_name;
    $sort_name .= $last_name;

    if (!empty($first_name)) {
      $name .= ', ' . $first_name;
    }
  }
  elseif (!empty($first_name)) {
    $name = $sort_name = $first_name;
  }

  $entity->setName($name);
  $entity->setSortName($sort_name);
}

/**
 * Implements hook_entity_insert().
 */
function nbbib_core_entity_insert(EntityInterface $entity) {
  $entity_storage = \Drupal::entityTypeManager()->getStorage($entity->getEntityTypeId());
  $stored_entity = $entity_storage->load($entity->id());
  // Force pathauto generation on insert if the service is available.
  if (\Drupal::hasService('pathauto.generator')) {
    \Drupal::service('pathauto.generator')->updateEntityAlias($stored_entity, 'update');
  }
}

/**
 * Implements hook_entity_update().
 */
function nbbib_core_entity_update(EntityInterface $entity) {
  $entity_storage = \Drupal::entityTypeManager()->getStorage($entity->getEntityTypeId());
  $stored_entity = $entity_storage->load($entity->id());
  // Force pathauto generation on update if the service is available.
  if (\Drupal::hasService('pathauto.generator')) {
    \Drupal::service('pathauto.generator')->updateEntityAlias($stored_entity, 'update');
  }
}

/**
 * Implements hook_views_pre_render().
 */
function nbbib_core_views_pre_render($view) {
  if ($view->id() == 'nb_bibliography_citations') {
    // Include current collection in view title.
    if (!empty($view->getExposedInput()['collections_5'])) {
      $view->setTitle($view->getTitle() . ' - ' . $view->getExposedInput()['collections_5']);
    }
  }
}
