<?php

/**
 * @file
 * Contains nbbib_core.install.
 */

use Drupal\redirect\Entity\Redirect;

/**
 * Implements hook_install().
 */
function nbbib_core_install() {

  // Default redirects.
  // Redirect after delete.
  // Load reference types from configuration.
  $config = \Drupal::config('nbbib_core.settings');
  $types = $config->get('nbbib_types');
  $types = array_column($types, 'entity');
  $del_redirs = [];
  $works = [];

  foreach ($types as $type) {
    $del_redirs[] = "yabrm/$type";
    $works[] = substr($type, 6) . 's';
  }

  foreach ($del_redirs as $del_redir) {
    Redirect::create([
      'redirect_source' => $del_redir,
      'redirect_redirect' => 'internal:/bibliography',
      'language' => 'und',
      'status_code' => '301',
    ])->save();
  }

  // Breadcrumb redirects.
  // Contributors.
  Redirect::create([
    'redirect_source' => 'contributors',
    'redirect_redirect' => 'internal:/contributors/all',
    'language' => 'und',
    'status_code' => '301',
  ])->save();

  // Work redirects.
  foreach ($works as $work) {
    $work = ($work == 'thesiss') ? 'theses' : $work;
    Redirect::create([
      'redirect_source' => $work,
      'redirect_redirect' => 'internal:/bibliography',
      'language' => 'und',
      'status_code' => '301',
    ])->save();      
  }
  
  // Redirect SAML login.
  Redirect::create([
    'redirect_source' => 'login',
    'redirect_redirect' => 'internal:/saml/login',
    'language' => 'und',
    'status_code' => '301',
  ])->save();
}
