<?php

/**
 * @file
 * Contains yabrm.install.
 */

use Drupal\Core\Database\Database;

/**
 * Implements hook_update().
 * Add field description_v2 to yabrm_collection.
 */
function yabrm_update_8701(&$sandbox) {
  $spec = [
    'type' => 'varchar',
    'description' => 'Description  of the Bibliographic Collection entity.',
    'length' => 2048,
    'not null' => FALSE,
  ];

  $schema = Database::getConnection()->schema();
  $schema->addField('mytable1', 'newcol', $spec);
}
