<?php

/**
 * @file
 * Contains yabrm.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yabrm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the yabrm module.
    case 'help.page.yabrm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Yet Another Bibliographic Reference Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function yabrm_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  $entity_types = [
    'yabrm_collection',
    'yabrm_contributor',
  ];

  // Load reference types from configuration.
  $config = \Drupal::config('nbbib_core.settings');
  $ref_types = $config->get('nbbib_types');
  $ref_types = $ref_types ? array_column($ref_types, 'entity') : NULL;
  // Add them to entity types array.
  $entity_types = array_merge($entity_types, $ref_types);
  
  if (in_array($hook, $entity_types)) {
    $view_mode = $variables['elements']['#view_mode'];
    $suggestions[] = "{$hook}__" . $view_mode;
  }
}

/**
 * Implements hook_theme().
 */
function yabrm_theme() {
  $theme = [];

  // Set up to use custom Collection entity template.
  $theme['yabrm_collection'] = [
    'render element' => 'elements',
    'file' => 'yabrm_collection.page.inc',
    'template' => 'yabrm_collection',
  ];
  $theme['yabrm_collection_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'yabrm_collection.page.inc',
  ];

  // Set up to use custom Contributor entity template.
  $theme['yabrm_contributor'] = [
    'render element' => 'elements',
    'file' => 'yabrm_contributor.page.inc',
    'template' => 'yabrm_contributor',
  ];
  $theme['yabrm_contributor_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'yabrm_contributor.page.inc',
  ];

  // Set up to use custom Biblio Reference entity template.
  $theme['yabrm_biblio_reference'] = [
    'render element' => 'elements',
    'file' => 'yabrm_biblio_reference.page.inc',
    'template' => 'yabrm_biblio_reference',
  ];
  $theme['yabrm_biblio_reference_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'yabrm_biblio_reference.page.inc',
  ];

  // Load reference types from configuration.
  $config = \Drupal::config('nbbib_core.settings');
  $ref_types = $config->get('nbbib_types');
  $ref_types = $ref_types ? array_column($ref_types, 'entity') : NULL;
  
  // Build template suggestions for reference types.
  foreach($ref_types as $ref_type) {
    // Set up to use custom type entity template.
    $theme[$ref_type] = [
      'render element' => 'elements',
      'file' => "$ref_type.page.inc",
      'template' => $ref_type,
    ];
    $theme[$ref_type . '_content_add_list'] = [
      'render element' => 'content',
      'variables' => ['content' => NULL],
      'file' => "$ref_type.page.inc",
    ];

    // Set up to use custom reference Citation view mode for type.
    $theme[$ref_type . '__citation'] = [
      'template'  => 'yabrm_biblio_reference__citation',
      'base hook' => $ref_type,
    ];
  }
  
  return $theme;
}
