_core:
  default_config_hash: PyIxbZYPmr87P0HYAohANvtLUa0_-_Cjtcr8du2OpcU
langcode: en
status: true
id: nbbib_core
Label: 'NBBIB Core'
module: nbbib_core
description: 'Provides configuration options for nbbib_core'
core: 10.x
nbbib_types:
  -
    entity: yabrm_book
    singular: Book
    plural: Books
  -
    entity: yabrm_book_section
    singular: 'Book Section'
    plural: 'Book Sections'
  -
    entity: yabrm_journal_article
    singular: 'Journal Article'
    plural: 'Journal Articles'
  -
    entity: yabrm_thesis
    singular: Thesis
    plural: Theses
  -
    entity: yabrm_conference
    singular: 'Conference Proceeding'
    plural: 'Conference Proceedings'
  -
    entity: yabrm_report
    singular: Report
    plural: Reports
  -
    entity: yabrm_periodical
    singular: Periodical
    plural: Periodicals
  -
    entity: yabrm_film
    singular: Film
    plural: Films
view_headers:
  nbbib_essays: 'Enter custom view header text here.'
