favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://localhost:3097/themes/contrib/unb_lib_theme/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  unb_lib_theme: 8000
  nbbib_lib_unb_ca: 8000
features:
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
  node_user_picture: false
logo:
  path: ''
  url: ''
  use_default: 1
table_responsive: '-1'
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
reset_http_request_cache: ''
table: ''
forms_smart_descriptions: 0
